app/scripts/controllers/item.js, app/views/item.html, lib/web.js
Thanks for this great project. This adds a display option for the source file.
=> View email source. Closes djfarrelly/MailDev#10.

lib/mailserver.js
=> Create /tmp/maildev if it doesn't already exist

app/scripts/controllers/item.js, app/views/item.html, lib/mailserver.js, lib/web.js
Add option to download email as .eml file (Issue: #51)
=> Add link to download EML

app/index.html, app/scripts/controllers/main.js
First, thank you for this really nice package !
I just added the count of unread items in the title, so now we can see, f.e., (5) MailDev.
=> added unread items count in the <title>

README.md
Hi, not really a PR.
Just that I developed a grunt task to run a MailDev server ([grunt-maildev](https://github.com/xavierpriour/grunt-maildev)) and I thought it would be interesting to mention it in your README, so I added a few words there.
Let me know if you're ok with that.
=> Announcing grunt-maildev

.travis.yml, README.md, package.json
For better automated testing for pull requests.
=> Add travis-ci for tests

index.js, lib/mailserver.js, lib/web.js, package.json, test/api.js, test/mailserver.js
This adds test coverage for #58
=> Add mailserver smtp tests

lib/mailserver.js, package.json, test/send.js
Building on #74 to address #30, this includes a questionable approach including 2 packages and forking the code based on the parsed version of Node. Would love feedback on this approach if there suggestions or improvements.
=> Add new smtp server for Node >= 0.12.x

README.md, docs/api.md, index.js, lib/mailserver.js, package.json
Adding an auto relay mode
See #80 for more details.
=> Add auto relay mode

README.md, app/scripts/app.js, app/scripts/controllers/main.js, docs/api.md, index.js, lib/mailserver.js, lib/web.js, package.json
=> 0.12.0 Release

.jshintrc, .travis.yml, Gruntfile.js, app/scripts/controllers/item.js, app/views/item.html, index.js, lib/logger.js, lib/mailserver.js, lib/outgoing.js, lib/routes.js, lib/web.js, package.json, test/api.js, test/mailserver.js, test/send.js
This is a placeholder to track development status of the 0.12.1 release
=> 0.12.1 Release

lib/mailserver.js, package.json
When I sent 2 emails at the same time in MailDev, i had an SMTP error. 
So I delayed email sending through a queue.
=> Adding async queue for relaying email in order to fix bug when bulk send

index.js, lib/mailserver.js, lib/outgoing.js, lib/web.js
To address the issue described in #118. This causes an immediate shutdown when using `docker stop`.
=> Shutdown on SIGTERM signal

.travis.yml, README.md
To add automated code coverage and a badge on the repo to encourage better code coverage on project.
=> Add basic code coverage

.gitignore, package.json, test/email.js
To encourage more test coverage for project
=> Add code coverage with Istanbul

lib/web.js
Prefixed "app" with web + prefixed URL with http:// to make it clickable in supported clients.
=> Improved log line when running maildev

README.md, index.js, lib/mailserver.js, package.json, test/api.js
To merge and make adjustments for #147.
=> Adjustments for merging #147

.dockerignore, Dockerfile
Reduce the number of layers in the Docker image by dropping the excessive `ADD` and `RUN` steps.
Also removes the unminified javascript and source maps from image.
=> Reduce Docker image layer

scripts/dev.js
This should fix https://github.com/djfarrelly/MailDev/issues/179
=> fixes #179

README.md, index.js, lib/mailserver.js, lib/outgoing.js
=> option --auto-relay-all-to-address <email>

README.md, app/views/main.html
Pick up a couple of changes that were applied directly to the master branch.
=> merge from master

.gitignore, .travis.yml, Dockerfile, app/scripts/app.js, app/scripts/controllers/item.js, app/scripts/controllers/main.js, codecov.yml, index.js, lib/mailserver.js, lib/outgoing.js, lib/routes.js, package-lock.json, package.json, test/outgoing.test.js
=> Upgrading to NodeJS 8 LTS version

docs/rest.md, lib/auth.js, lib/routes.js, test/auth.test.js
=> feat(rest): Add health checks

index.js, test/outgoing.test.js
Fix typos in var names and logger.
=> Fix typos in var names and logger.

README.md, app/views/main.html, docs/docker.md, package.json
To update all other references to the new locations which are owned by the Maildev org and not me.
Hey @oktapodia, just a heads up on this one!
=> Update Docker & Github repo referencess

README.md, index.js
Here's a PR that adds the possibility of using environment variables to configure MailDev, which is very useful with the Docker image.
=> Allow configuration from environment variables

README.md, index.js, lib/options.js, package.json, scripts/updateUsageREADME.js, test/options.test.js
Adding structure around this will allow us to add tests and consistency w/ options and environment variables. This also allows for the auto-generation of the the usage docs.
=> Extract options parsing as library

Dockerfile, package-lock.json, package.json
detail:
- fix dev script, update maintainer list, update version, update deps to fix npm fetch nodemailer
- update dockerfile
- release new docker image
=> feat: upgrade docker image and package.json

example-sendmail.js
ref: https://github.com/maildev/maildev/pull/369
=> chore: update sendmail example for bcc

test/cli.test.js
ref: https://github.com/maildev/maildev/pull/368
=> chore: update test for cli

lib/routes.js, package-lock.json, package.json
ref: https://github.com/maildev/maildev/pull/305
=> feat: Api with compression

docs/rest.md, lib/routes.js, lib/utils.js, test/middleware.test.js, test/utils.test.js
https://github.com/maildev/maildev/pull/334
=> feat: email api support filter

README.md
ref: https://github.com/maildev/maildev/pull/311
=> chore: Improve wording

docker/Dockerfile, docker/package-lock.json
detail: https://github.com/maildev/maildev/issues/396
=> chore: provide stable lockfile for node v16 (#396)

package.json, scripts/dockerBuild.sh, scripts/dockerPush.sh
Some changes to improve publishing of the npm package or Docker images.
=> Publishing workflow improvements

LICENSE, vendor/mailparser-mit/LICENSE, vendor/mailparser-mit/lib/charset/charsets.js, vendor/mailparser-mit/lib/charset/iconv-loader.js, vendor/mailparser-mit/lib/charset/index.js, vendor/mailparser-mit/lib/datetime.js, vendor/mailparser-mit/lib/libmime/index.js, vendor/mailparser-mit/lib/libqp/index.js, vendor/mailparser-mit/test/charset.test.js, vendor/mailparser-mit/test/libmime-test.js, vendor/mailparser-mit/test/libqp-unit.js, vendor/smtp-connection/LICENSE
Updated the year to the current year
=> year update

Dockerfile
Added MAILDEV_BASE_PATHNAME env variable to healthcheck
=> Fixed healthcheck with MAILDEV_BASE_PATHNAME

.devcontainer/devcontainer.json, .vscode/launch.json, README.md, lib/mailserver.js
Hi, I was just investigating a bug (which was no bug in the end) and added some configuration for it: 
- devcontainer.json for developing inside a docker container
- launch.json for debugging the application
Feel free to merge or close if you are not interested in IDE specific configurations.
=> add devcontainer and launch.json

README.md
To use the SMTP server for the spring boot app, I have added the configuration for the `application.properties` file or `application.yml` file
=> spring boot configuration added

README.md
Thanks for your awesome project with this nice REST API. I’ve added some minor language improvements for the documentation. Hope that helps! :v:
=> Documentation language improvements

lib/auth.js, lib/web.js, test/auth.test.js
fix #474
health check failed with auth and basepathname != /
=> fix: health check with auth and basePathname

lib/outgoing.js
=> fix(420): maildev does not fail to start when using --auto-relay together with --mail-directory

Dockerfile, docs/docker.md
As the title says, this PR aims to add the possibility to set container timezone.
=> feat: possibility to set timezone

package-lock.json, package.json
Fixes:
* https://github.com/maildev/maildev/security/dependabot/64
* https://github.com/maildev/maildev/security/dependabot/65
* https://github.com/maildev/maildev/security/dependabot/55
* https://github.com/maildev/maildev/security/dependabot/66
* https://github.com/maildev/maildev/security/dependabot/50
=> Update deps to fix vulnerabilities

.github/workflows/test.yml, example-sendmail.js, lib/mailserver.js, package.json, test/api.test.js, test/email.test.js, test/middleware.test.js
The entire test suite is a bit flaky now due to the way that emails must be waited for using event emitters.
=> Remove test account creation to fix flaky tests
