maildev/maildev

app/scripts/controllers/item.js

This pull request addresses issue #60. Instead of performing a full refresh and redrawing the whole UI, this will, upon a successful delete, first of all find the email element for the email being deleted, navigate to the root path if the email is currently selected, and then remove the email element from its parent.

Prevent full refresh of UI when deleting a single email

---

README.md
index.js
lib/web.js

Added HTTP auth option, following from a requirement internally, and Issue #47 
I'm not sure if the way I've done this is correct or not, but it appears to work for our setup. I've had to override the 'listen' export originally provided by 'server', as the static route was allowing bypass of the auth middleware.
If you can think of improvements to be made to this, I'm all ears. Relatively new to NodeJS (though not JS), so completely open to criticism.
Thanks

Adding HTTP auth options

---

README.md
index.js
lib/mailserver.js

Due to the requirement of having a public-facing SMTP server for testing purposes, I decided to implement authentication in MailDev, by adding a couple of command line options, and adding the required instantiation options to the simplesmtp instance, as well as the required authorizeUser event.

Adding the ability to require authentication on the SMTP server

---

README.md
index.js
lib/mailserver.js
lib/web.js

This pull request adds the ability to specify the binding IP address for the HTTP and SMTP services. To prevent breaking any existing versions, this defaults to '0.0.0.0', as the current version binds to all IP addresses (instead of 127.0.0.1, as the console log suggests).
Added in relation to issue #11

Add ability to specify binding IP address for services

---

bin/maildev
docs/api.md
index.js
lib/mailserver.js
test/api.js

There was no way to run the maildev server programmatically and ensure the smtp server was running via callback. Breaking changes:
* Instantiating MailDev's exported function no longer starts the smtp server
* The old `listen` method has been replaced with two methods:
* `create` - this accepts the options arguments as the old `listen` method used to
* `listen` - this starts the smtp server and accepts a single callback which is called when the smtp server is up and running

[Breaking] Change API listen method. Add create method.

---

README.md

As I understand it, calling `listen()` wasn't needed before v0.10... this change to the README may help to avoid confusion.

Add .listen() to the API example

---

app/scripts/app.js
app/scripts/controllers/item.js
app/scripts/controllers/main.js
lib/mailserver.js
lib/web.js

Essentially moved the behaviour of the delete mail to a socket event, instead of straight after the delete is submitted. This means an email will only be removed from the GUI if the server has actually deleted it, and also means the delete will be broadcast to other users.

Emit socket event on delete djfarrelly/MailDev#70

---

lib/mailserver.js
package.json

RE djfarrelly/MailDev#30
I've tested receiving emails with and without attachments, as well as relaying with and without authentication. All appears to work, however I'm not sure about the definitions of the callbacks in lib/mailserver.js around lines 417-466 (in particular mailConnectCallback and mailSendCallback). Open to suggestions as to how it can be improved - it just feels messy scoping them like that.
The change to smtp-server and smtp-connection does require NodeJS 0.12, as it depends upon Sets, which became available with 0.12.

Replace simplesmtp with smtp-server and smtp-connection djfarrelly/MailDev#30

---

app/scripts/app.js
app/scripts/controllers/main.js
index.js
lib/web.js

I'm using MailDev as my mail server for local tests, and now want to use it for my staging environment as well. Best way to be sure my pre-prod mails don't end up in actual client mailboxes...
Issue is, the staging server is out there in the cloud, so in order to access the HTTP front from my development machine, I need to bind the http server to 0.0.0.0 (and secure with user+password), but I do not want to expose the SMTP port to the internet (keep it bound to 127.0.0.1)
So I added a `--web-ip` option to specify which address to bind the web front to.
For backward compatibility with #63, if only `--ip` is specified it binds http to it as well.
PS: I also fixed 3 jshint complaints in unrelated files, to get a clean build.

Add option to bind HTTP front to different address than SMTP server

---

lib/mailserver.js

Hi,
these two commits allow us to relay incoming mails. diresis commit ensures, that there is no "null" recipient or sender and the other commit closes the smtp connection after sending an email. This was necessary because we always got an error when the connection was closed by the smtp server.
Cheers
Christian

Connection close and relay

---

Dockerfile

Basically the same `Dockerfile` as [`node:5-onbuild`](https://github.com/nodejs/docker-node/blob/c4868ce25f75d47e3ec75e6479664d8c46fc990e/5.4/onbuild/Dockerfile) but based on `slim` image.
Built image size on master: 715.6 MB 
Built image size on my PR: 278.4 MB
With this, you're saving **437,2 MB** of space, it's quite huge.
I think Docker should create a `slim-onbuild` tag on the official repository.

Save space on Docker image by using node:slim

---

lib/web.js

This PR addresses the issue seen in more modern node versions. The path for the static files appears to be traversing one level too many. I've removed the extra level of traversal and am making use of the `path` module to join the paths together.
I've tested this solution on versions v0.10.40, v0.12.7 and v5.7.1. In all three versions the GUI displays as expected. This was tested by updating to the target `node` versions and installing the `maildev` package on each using `npm`. The change was also tested by cloning the project down in each version, and then running `bin/maildev`.
This resolves issue #106 
p.s. Nice to see this is still going @djfarrelly - love the additions! :+1:

Fixing path to static directory

---

app/scripts/app.js
app/views/item.html
docs/api.md
index.js
lib/routes.js
lib/web.js

This PR enable using Maildev as a middleware of an existing app.
The README explains how it's achieved:
```
We can use maildev within an existing app by giving an additional parameter
`middleware` to the options object. We use a proxy to redirect all maildev requests
to the maildev app.
```
Everything works fine when no middleware option is passed.
Feedbacks are welcome :)

Using maildev as a middleware

---

Dockerfile

Switch from node:5-slim to alpine:3.3 to reduce the image size (~270MB to ~42MB).
I also apply some cleanup commands so as to decrease the overall size of the image.
To be fair, I started this work because the standard image was segfaulting on my system (I wonder if it does that to other) and I didn't wanted to mess with the node image.

Reduce the size of the Docker image by switching to alpine base image

---

lib/mailserver.js

using the global flag on the search regexp applies replacement for all
matches in the document.
fixes #116

fix all inline images

---

lib/mailserver.js
lib/web.js
package.json
test/mailserver.js

We now shout down the server with an error message that it could not be started, if MailDev was unable to bind the ports. See #159

Trying to solve issue #159

---

Dockerfile
index.js
lib/web.js
package.json

Originally intended to fix #156 after testing #157 and it wasn't working during my local debugging. This now handles and destroys all open socket connections which makes the web server shut down immediately.
This also has other improvements around the Docker image and some items that I should have 
Hey @jsonxr and @donut87, this should fix #156 up! Would love to see if you had any comments or feedback for this!

Better shutdown handling

---

app/scripts/controllers/item.js

The server side uses MailParser's `streamAttachment` option to improve performance on emails with large attachments. However, the client app requests `/email/:id/html` and `/email:id/source` on item load. This moves the source call to only occur when Display --> Source is clicked.

Change source request to be lazy

---

README.md
index.js
lib/mailserver.js
package.json
test/api.js

I needed to test ASCII-only headers so I added this option to be able to keep the server from sending the  `SMTPUTF8` extension in the `EHLO` response.
Functionality for hiding this extension (as well as `PIPELINING` and `8BITMIME`) was added in `smtp-server` 1.10.0 so while I was at it I upgraded the `smtp-server` dependency from 1.4.0 to 1.16.1. All tests still pass after adding a newline to the end of the test mail body (see [`smtp-server` 1.11.2](https://github.com/andris9/smtp-server/blob/master/CHANGELOG.md#v1112-2016-07-15)).

Add --hide-extensions option that can be used to not advertise certain SMTP extensions

---

lib/web.js

Wasn't working because io.path doesn't work when attaching a server to an already defined socket.io object
closes #176

Passing of basepath changed to a require call

---

app/views/main.html

Usually, we don't display a period between the `v` and the version number.

Fix version display in GUI

---

lib/web.js

A path gets converted to using \ instead of / on Windows. This pull fixes it.

Fixes #185 on Windows

---

docs/docker.md

This PR adds some simple documentation for using MailDev with Docker Compose.
Partially addresses Issue #115.

Add documentation for docker-compose usage

---

README.md

Disable TLS in Rails' configuration example, as it's not supported.

Correct the configuration example for Rails (Fix #234)

---

lib/mailserver.js

This PR adds URL encoding of attachment file names. Previously when attached image names contained characters than needed escaping, they would fail to display in HTML view. With this PR, the attachment names are correctly escaped and appear in HTML view.

URI encode attachment file name

---

lib/web.js
package-lock.json
package.json

Enables calling the rest API from elsewhere, like from cypress tests.
Probably replaces #218 and fixes #211

Add cors to the rest API

---

app/index.html
app/scripts/controllers/main.js
app/scripts/services.js

As mentionned in https://github.com/djfarrelly/MailDev/issues/251, an unread counter placed in the favicon is more readable if the maildev tabs is pinned.

Add an unread counter in the favicon

---

README.md
index.js
lib/mailserver.js

Fixes #274 by always hidding STARTTLS extension, as TLS is not available et crashes the server.

Hide STARTTLS

---

Dockerfile
README.md
docs/docker.md
package-lock.json
package.json

This PR adds the following:
- **Change the default user from root to node in image**
Currently the user is set as root, which is unsafe. I have changed the user to the default node user, 
along with the working directory to /home/node, so that the dependencies and the app are owned by  the node user. Keep in mind that the node user can still overlap because of its id and group id (1000, 1000 respectively).  
- **Increase the default ports with 1000:**
Ports 80 and 25 are mostly reserved for other containers / host applications. These are changed to 
1080 and 1025, which better isolates this application for development. This fixes #244 and makes 
#273 obsolete. This is a needed fix for podman users as well, if ports '< 1024' aren't enabled in the 
user space.
- **Change the entrypoint to …

Remove root user from docker, update ports and update Node / libraries

---

app/views/item.html
index.js
lib/mailserver.js
lib/routes.js
package-lock.json
package.json
scripts/dev.js
scripts/send.js
test/mailserver.test.js
test/middleware.test.js

This adds an option to disable the execution of javascript in a mail.
By default Javascript will be executed with the flag --disable-javascript it can be disabled.

Enabling/disabling javascript - fixes #152

---

README.md
lib/options.js
lib/outgoing.js

Handle SMTPConnection errors gracefully. Fixes #287.
> If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits. ([source - Node.js official docs](https://nodejs.org/api/events.html#events_error_events))
- Without handling SMTPConnection's error, the app would always have a fatal error and exit
- Thanks to @heldchen for the fix as documented in #287

Handle SMTPConnection errors. Fixes #287.

---

index.js
lib/mailserver.js
lib/options.js
lib/routes.js

This PR add some new features :
- Persistence for mail can be used by using the option --mail-directory
- Can be used to mount a volume in a kubernetes/docker environment
- At startup reload mails in memory from the directory specified
- Add a new endpoint to force reload mail in memory from directory
Inspered by this PR https://github.com/maildev/maildev/pull/280 
Can address this issues :
- https://github.com/maildev/maildev/issues/44
- https://github.com/maildev/maildev/issues/299
The last point is usefull to adresses this issues : https://github.com/maildev/maildev/pull/237 & https://github.com/maildev/maildev/issues/127 cause you can add an external rules for purging mail in directory (ie: cron find file aged more than X days, delete it & trigger reload mail)
For a preview of usage …

Add persistence support 

---

.github/workflows/node.js.yml
.travis.yml

* Removes Travis
* Add Github Actions
* https://github.com/madflow/maildev/actions/runs/427974910
As far as I can see the Travis test are currently not visible/running. Github actions should be - and do not require a second vendor.

switch to Github actions

---

package.json

According to @danjarvis  suggestion, update the node version dependencies of the package

bugfix: update package.json declare that Node v12 or later is required

---

app/index.html
app/scripts/components/address.js
app/views/address.html
app/views/item.html
assets/styles/style.scss
lib/helpers/bcc.js
lib/mailserver.js
test/bccHelpers.test.js

As maildev is primarily a debugging tool we want to validate the correctness of TO, CC and BCC as well.
See #233 
- multiply the emails for each recipient
- show cc and bcc addresses in the preview
Duplicating emails won't help debugging and may make it even worse. So we went for the "show in preview" option. 
Bcc should not be contained in the mail source. Otherwise it wouldn't be a "blind" copy as the recipients could see the blind copy recipients. Every recipient (to, cc, bcc) should be part of the `RCPT` though. So from my understanding and the insight of this [Mailtrap article](https://mailtrap.io/blog/cc-bcc-in-smtp/) bcc should be `allRecipients - to - cc`. This calculated bcc is what I implemented and added to the stored parsed email.
On the GUI side I found that it's actually …

BCC support

---

app/scripts/controllers/item.js

Prior to the 2.0 release, the `iframe` was set at the highest level of the closure, but it no longer is, so instead of setting and reading that variable, this passes it as an argument or searches the page for it.
Fixes #398, #411, #403

Ensure iframe is not undefined.

---

docker/package-lock.json
lib/mailserver.js
package-lock.json
package.json
scripts/resources/punk-bands.html
scripts/resources/simple-form.html
scripts/resources/sources.txt
scripts/send.js
test/email.test.js
test/middleware.test.js

Use [strip-js](https://www.npmjs.com/package/strip-js) to sanitise html content instead of `turndown` + `marked` libraries.
`strip-js` removes all javascript from the html while preserving everything else. The combination of `turndown` + `marked` to convert html to markdown and back corrupts the html in certain cases.
Other changes:
- Added a test to confirm that html table elements are not corrupted (fails in verison 2.0.2)
- Added another example email to send.js script containing a heavily styled html table
- Fixed other failing tests caused by using strip-js (better preservation of html content)
Fixes #398

Use strip-js to sanitise html content

---

.github/workflows/test.yml
.gitignore
.vscode/settings.json
app/scripts/controllers/item.js
lib/mailserver.js
package-lock.json
package.json
test/email.test.js
test/middleware.test.js

While Node 18.x is still not Active LTS and we may not completely support it, this is an easy fix to land and start running our tests against 18.x.
Fixes #413.

Upgrade smtp-server dep for Node 18.x fix

---

Dockerfile
package.json

Ola,
this is just a minor update, upgrading socket.io version on package.json to 4.6.0, which fixes some vulnerabilities (CVE-2022-41940 and CVE-2022-2421 -- actually those were flagged in the package dependencies).
Tested locally and found no issues on the app behavior, but I honestly didn't go through the whole code to analyze the impact of this update.
Also, it'd be nice to update the dockerhub image -- there are several other CVEs that can be fixed with the latest node:16-alpine image (or another more up-to date node version as well, but the vulns were at the alpine image itself).
Currently there's only one vulnerability still listed for this image (based on AWS Inspector): CVE-2022-25881 - http-cache-semantics -- which is actually a core npm dependency (not the app's), still to check …

upgrade socket.io to fix CVE-2022-41940 and CVE-2022-2421

---

lib/mailserver.js

Currently, when you have a link in your email, maildev removes "target=_blank" on anchors.
e.g.
`<a href="...." target="_blank" />` is sanitized into  `<a href="..." />`
This PR adds the "target" attribute to the allowed items.
Partially fixes: https://github.com/maildev/maildev/issues/457

Dont sanitize target=_blank attributes on anchors.

---

lib/helpers/smtp.js

There is an issue for this problem https://github.com/maildev/maildev/issues/436
The problem is that when logging in to an smtp server with username and password configured, you can log in by passing an arbitrary username and an empty password. This is due to an error in the authorization logic implemented in the file smtp.js.
The playback path:
```docker run -p 1080:1080 -p 1025:1025 --name maildev maildev/maildev --incoming-user test --incoming-pass password```
```telnet localhost 1025
EHLO localhost
AUTH LOGIN
334 VXNlcm5hbWU6
admin
334 UGFzc3dvcmQ6
235 Authentication successful
```
This PR fixes this bug

Fix auth with no password

---

README.md
lib/mailserver.js
lib/options.js
lib/web.js

Should fix #484 
Maildev currently listens on IPv4 only, which causes the healthcheck to fail with some Docker versions or custom daemon settings. Most dockerized apps that I've seen listen on both IPv4 and IPv6.
This should be documented as a breaking change to avoid unwanted exposure of Maildev in case someone has a particular config (for example a Docker daemon configured to use a public IPv6 block)

Listen on IPv4 and IPv6 by default

---

lib/helpers/attachments.js
lib/helpers/files.js
lib/mailserver.js
package.json
scripts/send.js
test/email.test.js

Builds on the idea in #487 to prevent file name injections with the `Content-ID` header. 
Fixes CVE-2024-27448. 
Fixes #487.
Previously, the `Content-ID` header was directly used to write temporary attachment files to disk. This was problematic as the code was writing the file to disk with a simple `path.join` and the `Content-ID` could contain any characters including a relative path prefix. This allowed the attachment to be saved in any directory on disk. 
The fix for this is to always transform the attachment object as it is parsed from Mailparser and generate our own filename. The generated filename is a hash of the content id with the original file extension. This hashing prevents any relative pathnames from being used.
This also centralizes some logic in an attempt to prevent future …

Hash filename to prevent file name injections via Content-ID header.
